### ISSUE TITLE
Dashboard in infinite redirect loop with custom domain

### ISSUE THREAD

**Issue by tombh** [rancher/rio#1002]
When visiting https://dashboard-rio-system.rio.customdomain.com there's an infinite redirect loop.

**To Reproduce**
Rio install _without_ Lets Encrypt and RDNS. Set up a custom domain with:
```
apiVersion: admin.rio.cattle.io/v1
kind: ClusterDomain
metadata:
  name: example.com
spec:
  httpPort: 80
```

I'm using my own Nginx ingress and cert-manager installs on the same cluster in order to manage my own wildcard domain certs. The ingress's backend is `gateway-proxy`, all other apps setup in my Riofile work fine.

Kubernetes 1.16 on Digital Ocean. Rio v0.7.0

Maybe Rio's trying to redirect to HTTPS because Nginx is only forwarding it the 80 port?
