### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by harshsharma22** [rancher/rio#1032]
**Feature Utilization**

**To Reproduce**

1. start multiple service and in one service try adding name of the service to route

**Expected behavior**
should be able to route

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```

```
Type:
**Rio version**: `rio info`
```
version 0.0.7
```

**Comment by j-wil** [comment]
I believe I am running into the same issue.
```
Rio Version: v0.8.0 (af7ad687)
Rio CLI Version: v0.8.0 (af7ad687)
```
Runnin on AKS 1.17.11

```
routers:
  abc:
    routes:
      - match:
          path: 
            exact: /users
        to:
          - app: abc-ui
            namespace: abc
            port: 80
      - match:
          path: 
            regxp: /password.*
        to:
          - app: abc-users
            namespace: abc
            port: 8180
      - match:
          path: 
            regxp: /tokens.*
        to:
          - app: abc-users
            namespace: abc
            port: 8180
```
