### ISSUE TITLE
 ConfigMap as container environment variables

### ISSUE THREAD

**Issue by boredland** [rancher/rio#1039]
Is there a way to use configMaps to configure the environment variables in a container in this style?

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables

Something like in the official docs is what I search:
```
pods/pod-configmap-envFrom.yaml 

apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: special-config
  restartPolicy: Never
```
