### ISSUE TITLE
run --user & --group are not being set

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#258]
Version - v0.1.1-rc1

Steps:
1.  rio run -n tuser --user 10 --group 5 nginx
2.  rio exec default/tuser id
3.  rio inspect default/tuser:v0

Results:  user nor group id has been set

**Comment by StrongMonkey** [comment]
Will be fixed in https://github.com/rancher/rio/pull/342

**Comment by rancher-max** [comment]
Working in v0.6.0-alpha.2

Result snippet:
```
...
spec:
  image: nginx
  imagePullPolicy: IfNotPresent
  ports:
  - port: 80
    protocol: HTTP
    targetPort: 8080
  runAsGroup: 5
  runAsUser: 10
  weight: 100
...
```
