### ISSUE TITLE
non cluster-admin access for rio

### ISSUE THREAD

**Issue by debianmaster** [rancher/rio#266]
When i login a non cluster-admin role , im unable to use `rio` 
what is the proper RBAC i need to provide a regular user? to be able to use rio

**Comment by debianmaster** [comment]
```sh
No configuration found to contact server.  If you already have a Kubernetes cluster running then you should point your Kubernetes cluster using


	export KUBECONFIG=/path/to/config
```

Im seeing ^   error in this scenario

**Comment by StrongMonkey** [comment]
Rio need cluster-admin privilege but it is going to change in the future to only set the minimal set of rules. There is an issue that Rio doesn't work well with auth plugin inside KUBECONFIG.(https://github.com/rancher/rio/pull/264). Do you happen to have that in your KUBECONFIG?

**Comment by debianmaster** [comment]
@StrongMonkey  thanks for quick reply.      rio works fine for a user with cluster-admin priv  for me. 
for a regular user (namespace owner)   it shows `No configuration found to contact server.  If you already have a Kubernetes cluster running then you should point your Kubernetes cluster using
`   error.       i think i do not have the auth plugin issue that is highlighted by you

**Comment by jpapejr** [comment]
@StrongMonkey Is #282 related to your point about auth plugins?

**Comment by debianmaster** [comment]
My question is more on rbac here Vs Auth type afiak.   For same cluster a user with cluster admin priv worked but not working for less priv user

**Comment by debianmaster** [comment]
@StrongMonkey   may be my question was not clear.    how do i give `rio run` access to developers who do not have cluster-admin access ?   i have installed rio on rancher

**Comment by StrongMonkey** [comment]
@debianmaster Developers only need to have access to resources in `rio.cattle.io`.(which has basic rio type Service, ExternalService, Router). As long as they are able to create rio services. https://github.com/rancher/rio/issues/298 We are still working on this issue which can cause privilege escalation, but in the future will only need access resource in that group.

**Comment by debianmaster** [comment]
@StrongMonkey   i gave following permission but no luck.

> cluster role
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rio-reader
rules:
- apiGroups: ["rio.cattle.io"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
```

> rolebinding
```yaml 
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: rio-read
subjects:
- kind: User
  name: u-u5lc4sfnf7 
  apiGroup: rbac.authorization.k8s.io        
roleRef:
  kind: ClusterRole
  name: rio-reader
  apiGroup: rbac.authorization.k8s.io
```

**Comment by StrongMonkey** [comment]
@debianmaster Thanks for trying. I will take a look at this.

**Comment by rancher-max** [comment]
**This is fixed in latest version of rio. Validated with v0.7.0.**
Rio now provides out of the box clusterroles: `rio-admin`, `rio-cluster-admin`, `rio-privileged`, `rio-readonly`, and `rio-standard`. For reference to a previous comment in this thread regarding read rules, the `rio-readonly` role is supplied as:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rio-readonly
rules:
- apiGroups: ["rio.cattle.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["taskruns"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps", "extensions"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
```

Steps for my validation:
1. Create ClusterRoleBinding to the readonly role for a made up user: `kubectl create clusterrolebinding testuser --clusterrole=rio-readonly --user=testuser`
2. Add a user and context using that user to my kubeconfig file. Relevant portions:
```
- context:
    cluster: test
    user: testuser
  name: test
- name: testuser
  user:
    as: testuser
    password: fakepass
    username: fakeuser
```
3. Use that context: `kubectl config use-context test`
4. Quick check on permissions:
```
$ kubectl auth can-i create services.rio.cattle.io
no
$ kubectl auth can-i list services.rio.cattle.io
yes
```
5. `rio ps` works as expected
6. `rio run nginx` fails as expected: `FATA[0000] services.rio.cattle.io is forbidden: User "testuser" cannot create resource "services" in API group "rio.cattle.io" in the namespace "default" `
