### ISSUE TITLE
Monorepo support for the build system

### ISSUE THREAD

**Issue by oscartbeaumont** [rancher/rio#324]
Hello,
I am planning on developing a group of microservices on Rio and would like them to all stay inside a single repository so they are easier to work on and so breaking changes can be pushed to all of the services at the same time. Is it possible to achieve this in Rio? Could an option be added to use a subdirectory of the git repo as the root directory for the build or alternative Dockerfile path?
Thanks

**Comment by StrongMonkey** [comment]
@oscartbeaumont In the coming release(v0.2.0) Rio will be supporting custom dockerFile path and custom buildcontext directory. So in theory you could use a single repository and give different buildcontext for different services.

**Comment by oscartbeaumont** [comment]
That's awesome do you have a timeframe on the release of v0.2.0?

**Comment by StrongMonkey** [comment]
@oscartbeaumont Should be available in this week. We will also be adding more documentations around that.

**Comment by oscartbeaumont** [comment]
Thanks

**Comment by oscartbeaumont** [comment]
I saw that another prerelease for v0.2.0 was released today if you point me in the correct direction as to how to make this work I would be willing to put together an example.

**Comment by StrongMonkey** [comment]
@oscartbeaumont In v0.2.0-rc2 we add `--build-context` in `rio run` so you can choose custom buildPath. Let me know if that works for you.

**Comment by oscartbeaumont** [comment]
From the Kubernetes CRD?
Thanks for your help.

**Comment by StrongMonkey** [comment]
@oscartbeaumont 
The usage should be `rio run --build-context ./foo ${repo_url}`, assuming your subdirectory code lives in ./foo`.

**Comment by oscartbeaumont** [comment]
I mean in [build.yml](https://github.com/rancher/rio/blob/master/examples/build.yaml)?

**Comment by StrongMonkey** [comment]
try this 
```
apiVersion: rio.cattle.io/v1
kind: Service
metadata:
  name: $name
  namespace: default
spec:
  build:
    branch: master
    buildContext: ./foo
    dockerFile: Dockerfile
    repo: $repo
    template: buildkit
  concurrency: 10
  imagePullPolicy: IfNotPresent
  maxScale: 10
  minScale: 1
  ports:
  - port: 80
    protocol: HTTP
    targetPort: 8080
  rollout: true
  rolloutIncrement: 5
  rolloutInterval: 5
  scale: 1
  weight: 100
```
