### ISSUE TITLE
Local build

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#347]
Allow user to build repository based on local files in rio. If Riofile doesn't have image field set, rio will try to use the local context and build configs defined in Riofile. An example would be
```
services:
  register:
    global_permissions:
    - role=cluster-admin
    build:
      buildArgs:
      - MODULE=register
  controllers:
    global_permissions:
    - role=cluster-admin
    build:
      buildArgs:
      - MODULE=controllers
  clientapi:
    global_permissions:
    - role=cluster-admin
    ports:
    - 8080/http
    build:
      buildArgs:
      - MODULE=clientapi
  api:
    global_permissions:
    - role=cluster-admin
    ports:
    - 8080/http
    build:
      buildArgs:
      - MODULE=api
  agent:
    global_permissions:
    - role=cluster-admin
    build:
      buildArgs:
      - MODULE=agent
```

Then rio will use the current folder as the build context, with specific build arguments, build the image locally(stored in containerd) and replacing built images within services. Right now this only supports k3s with containerd runtime.
