### ISSUE TITLE
SecretRef and ConfigMapRef doesn't populate into environment variables

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#354]
Version: v0.3.0
Step to reproduce:
1. Create a `Riofile` to reference a secret name as an environment variable.
```
services:
  demo:
    image: nginx
    ports:
    - 80/http
    env:
    - name: FOO
      secretName: test
      key: foo
    scale: 1-20
```
2. SecretRef and configMap is not populated.
