### ISSUE TITLE
rio up w/ no Riofile

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rio#435]
If I run `rio up` in a directory with no Riofile I would like it to look for Dockerfile in the current directory.  If it does have `Dockerfile` then create an "virtual riofile"  as below

```yaml
services:
  current_path_name:
    port:
    - 80:8080/http
```
And then run up.

**Comment by rancher-max** [comment]
This is working in v0.6.0. It ends up creating a service with spec like:
```
spec:
  image: localhost:5442/default/rio-demo@sha256:83b5ad3c8b2b56b4516fa4f6c3a280e6962221e95a510ec078d7d56a3cd49e2a
  ports:
  - port: 80
    protocol: HTTP
    targetPort: 8080
```
