### ISSUE TITLE
Needs a https redirect feature

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rio#467]
Need to be able to redirect from http to https easily to force specific services/path to https only.

**Comment by lucidprogrammer** [comment]
Say you created a service like this,

`rio run --name sample -p 80:80 nginx:alpine`

```
rio ps
NAME      IMAGE          ENDPOINT                                     PORTS     SCALE     WEIGHT    CREATED          DETAIL
sample    nginx:alpine   https://sample-v0-default.somewhere.on-rio.io   80        1         100%      16 seconds ago  
``` 
Check the virtualservices you got 

```
kubectl get vs
NAME                                 AGE
sample                               110s
sample-tls-somewhere.on-rio.io-tls      110s
sample-v0                            110s
sample-v0-tls-somewhere.on-rio.io-tls   110s

```

Ok, now we need every request coming on the version of your choosing to go to https.

kubectl edit vs sample-v0

Add the following snippet, under the routes.

```

- matcher:
        prefix: /
      redirectAction:
        httpsRedirect: true
      routePlugins: {}
```

Once applied, your spec part of the virtualservice will look something like this


```
spec:
  virtualHost:
    domains:
    - sample-v0-default.somewhere.on-rio.io
    routes:
    - matcher:
        prefix: /
      redirectAction:
        httpsRedirect: true
      routePlugins: {}
    - matcher:
        prefix: /
      routeAction:
        single:
          kube:
            port: 80
            ref:
              name: sample-v0
              namespace: default

```
