### ISSUE TITLE
Volume errors when used in Riofile

### ISSUE THREAD

**Issue by mbarlow** [rancher/rio#530]
**Cannot currently use volumes in Riofiles**
Specifying a volume in a Riofile causes the service to never be brought up. rio ps shows service in "Not Ready" status. rio logs shows an error with container named "". rio systemlogs shows errors of: is invalid: [spec.template.spec.containers[0].volumeMounts[0].mountPath: Required value, spec.template.spec.initContainers[0].volumeMounts[0].mountPath: Required value], requeuing

**To Reproduce**
1. create a Riofile with contents:
```
services:
  test5:
    image: your-image
    workingDir: /app/handlers
    volumes:
    - volume-name: /app/handlers
    ports:
    - 8080:80/http

    containers:
    - init: true
      name: foo
      image: ubuntu
      volumes:
      - volume-name: /app/handlers
      args:
      - "echo"
      - "hello world"

```

2. run rio up
3. verify issues with rio ps, rio logs, rio systemlogs

**Expected behavior**

The service would be created successfully with an emptydir volume mounted to: /app/handlers

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T18:57:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

using kind locally
```
Type:
**Rio version**: `rio info`
```
Rio Version: v0.5.0-rc1 (1c31fdc4)
Rio CLI Version: v0.5.0-rc1 (1c31fdc4)
Cluster Domain: 5ig5i8.on-rio.io
Cluster Domain IPs: 172.17.0.3
System Namespace: rio-system

System Components:
activator status: running
autoscaler status: running
build-controller status: running
buildkitd-dev status: running
cert-manager status: running
controller status: running
gateway status: running
istio-pilot status: running
registry status: running
webhook status: running
```
**note:** This same behaviour occurs on v0.4.0.

**Additional context**
`rio systemlog`
output:
```
rio-controller | E0927 16:38:57.882267       1 controller.go:117] error syncing 'default/test5': handler stack-service-object-controller: failed to create default/test5 apps/v1, Kind=Deployment for stack-service default/test5: Deployment.apps "test5" is invalid: [spec.template.spec.containers[0].volumeMounts[0].mountPath: Required value, spec.template.spec.initContainers[0].volumeMounts[0].mountPath: Required value], requeuing
```

Additionally, the documentation on Riofile is missing "name" on containers.

**Comment by StrongMonkey** [comment]
```
services:
  test5:
    image: ibuildthecloud/demo:v1
    workingDir: /app/handlers
    volumes:
    - volume-name:/app/handlers
    ports:
    - 8080:80/http
    containers:
    - init: true
      name: foo
      image: ubuntu
      volumes:
      - volume-name:/app/handlers
      args:
      - "echo"
      - "hello world"
```
@mbarlow Actually I just tried with this manifest it works for me. As talked in rancher-user slack, you should probably change both volume sections to be the correct format. We will correct the docs and add volume example that were missing.
