### ISSUE TITLE
rio up overrides services from different stacks without warning

### ISSUE THREAD

**Issue by apollo13** [rancher/rio#744]
**Describe the bug**
`rio up` with different stack names `--name test1/2` overrides services from the previous deploy without a warning. 

**To Reproduce**
Create a minimal `Riofile`:
```
services:
  nginx:
    image: nginx
    ports:
    - 80/http,webtest
    scale: 1
```
and run 
```
rio up --name stack1
rio up --name stack2
```

The second `up` silently takes over `stack1`. This is not to problematic in this instance but would be worse if those were two completly different `Riofile`s

**Expected behavior**

A warning/error should be displayed.
