### ISSUE TITLE
health-url param on rio run errors out

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#750]
`rio run --health-url http://locallost:80 nginx` doesn't work
Throw an validation error if you run it.

**Comment by StrongMonkey** [comment]
Actually appears to be a server side error

**Comment by StrongMonkey** [comment]
We should fix this v0.6.0 release.

**Comment by izaac** [comment]
`rio v0.6.0-rc1` and below versions error out with:

```
rio run --health-url http://localhost:80 -p 80 nginx
FATA[0000] Service.rio.cattle.io "modest-tu-5brlz" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"rio.cattle.io/v1", "kind":"Service", "metadata":map[string]interface {}{"creationTimestamp":"2019-11-14T21:48:29Z", "generateName":"modest-tu-", "generation":1, "name":"modest-tu-5brlz", "namespace":"default", "uid":"7eb1c50c-0728-11ea-88c9-42010aa80038"}, "spec":map[string]interface {}{"app":"modest-tu", "image":"nginx", "ports":[]interface {}{map[string]interface {}{"port":80, "targetPort":80}}, "readinessProbe":map[string]interface {}{"httpGet":map[string]interface {}{"host":"localhost:80", "port":80, "scheme":"HTTP"}}, "version":"v0"}}: validation failure list:
spec.readinessProbe.httpGet.port in body must be of type string: "integer"
```

Now the `--health-url` flag is properly setting the Readiness Check in the service:

```yaml
   spec:
      automountServiceAccountToken: true
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: epic-diffie-v0hrlzp
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            host: localhost
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
```

```
Rio Version: a3e458ef (a3e458ef)
Rio CLI Version: dev (HEAD)
Cluster Domain: xxxxxx.on-rio.io
Cluster Domain IPs: x.x.x.x
System Namespace: rio-system
Wildcard certificates: true
```
