### ISSUE TITLE
Logs should target taskrun pod

### ISSUE THREAD

**Issue by cbron** [rancher/rio#782]
* Right now we target the full taskrun and the actual service pod after build finishes, we should only target the taskrun build pod
* it should ignore init-containers (add flag to stern for this)
* it should use all 3 states

**Comment by rancher-max** [comment]
Looks like all the inits are gone. Now properly just seeing `step-build-and-push` and `step-git-source` when viewing the logs for a build.

There is additionally a cli flag that was added: `--init-containers` that will show the init containers on pods by default, but can be set to false if you don't want to see them. An example of this is:
1. Create a file named `Riofile` with the following data:
```
kubernetes:
  manifest: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: busybox:1.28
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
      - name: init-mydb
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup mydb; do echo waiting for mydb; sleep 2; done;']
```
`rio up -f /path/to/above/Riofile`
`rio logs --init-containers=false pod/myapp-pod`
`rio logs pod/myapp-pod` <<< will show init container log output
