### ISSUE TITLE
Add default and required options into riofile questions

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#845]
In v0.6.0, Riofiles support questions and answers. Questions in the Riofile look like:
```yaml
...
template:
  questions:
  - variable: FOO
    description: "Some description"
```

It would be nice if we could specify default values and set certain questions to required:
```yaml
...
template:
  questions:
  - variable: FOO
    description: "Some description"
    required: true
  - variable: BAR
    description: "other description"
    default: "MyDefaultValue"
```

Then if I were to run `rio up` with that in my Riofile, it would fail because I haven't specified an answers file, and an answer to `FOO` is required. It would also fail if I did specify an answers file that didn't have the label `FOO` in it.
