### ISSUE TITLE
go templated custom rio file fails to bring up stack.

### ISSUE THREAD

**Issue by lucidprogrammer** [rancher/rio#864]
**Describe the bug**

**To Reproduce**
1. 

Try the example riofile . This will work if the name of the file is the default, which is Riofile

It fails to bring up anything if the name is different

```
services:
{{- if eq .Values.FOO "BAR" and eq .Values.NAMESPACE "test" }}
  demo:
    image: ibuildthecloud/demo:v1
    ports:
    - 80
{{- end}}

template:
  goTemplate: true # use go templating
  envSubst: true # use ENV vars during templating  
  questions:  # now make some questions that we provide answers too
  - variable: FOO
    description: ""


```

**Expected behavior**

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```

```
Type:
**Rio version**: `rio info`
```

```
**Additional context**
`rio systemlogs`
output:
```

```

**Comment by StrongMonkey** [comment]
Available to test on master.

**Comment by rancher-max** [comment]
**I think this is working fine now in latest master, but I'd like to call out a few things:**


1. The go template above is invalid. The docs are updated now to reflect what that should look like. 

2. In v0.6.0, it had some weird behavior. Now, if there is invalid go templating, it will fail with a fatal template error. i.e: `FATA[0000] template: template:2:28: executing "template" at <and>: wrong number of args for and: want at least 1 got 0`

3. Setting `.template.goTemplate: false` but having go templates defined causes parsing errors, i.e: `FATA[0000] error converting YAML to JSON: yaml: line 3: could not find expected ':'`

4. Removing the `.template.goTemplate` entirely, but having go templates defined, tries to use `rio build` functionality, then fails with `FATA[0000] failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount285606376/Dockerfile: no such file or directory`.

5. Setting up something valid, whether in a file named Riofile or something different (I tried with `Riofile_main` and `testing.yaml`) works as expected now. The file I used:
```yaml
services:
{{- if (and (eq .Values.NAMESPACE "test") (eq .Values.FOO "BAR")) }}
  demo:
    image: ibuildthecloud/demo:v1
    ports:
      - 80
{{- end}}

template:
  goTemplate: true # use go templating
  envSubst: true # use ENV vars during templating
  questions:  # now make some questions that we provide answers too
    - variable: FOO
      description: ""
    - variable: NAMESPACE
      description: "The namespace"
```
And the command: `rio -n test up -f testing.yaml --answers answers.yaml`, where answers.yaml just contains: `FOO: BAR`
Please note that `rio up` does not create a namespace if it does not exist, so this will fail if the `test` namespace does not exist. 

6. `NAMESPACE`, while it is a default environment variable available for substitution, needs to be defined in `.template.questions` to be used in go template. There is no need to supply an answer for the NAMESPACE question. 

7. Given 6 above, there is a weird "hack", where if `.template.envSubst` is set to `true`, and `${NAMESPACE}` is used anywhere in the Riofile, then the go template sees it and it is not necessary in the questions. For example, this Riofile compiles and runs successfully, with the go template taken into account:
```yaml
services:
{{- if eq .Values.NAMESPACE "test" }}
  demo:
    image: ibuildthecloud/demo:v1
    ports:
    - 80
{{- end}}

this-is-not-used: ${NAMESPACE}

template:
  goTemplate: true # use go templating
  envSubst: true # use ENV vars during templating
```
