### ISSUE TITLE
Add `--dry-run` flag to rio up

### ISSUE THREAD

**Issue by cbron** [rancher/rio#866]
It's hard to figure out what your data and output will be while programming a Riofile. 
Example: Given our example Riofile, what is literal value of bar and namespace ?
```
{{- if and (eq .Values.FOO "BAR") (eq ..Values.NAMESPACE "test") }}
services:
  demo:
    image: ibuildthecloud/demo:v1
    ports:
    - 80
{{- end}}
```

We should do one of the following: 
* `--dry-run` in order to see full output manifest 
* `--values` in order to see all values/answers without executing riofile
