### ISSUE TITLE
[VISUAL ONLY] rio ps always shows first container in pod spec regardless of exposed ports

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#872]
**Describe the bug**
`rio ps` will always show the first container in the pod spec. Sometimes, this image is not the one that is being served by the endpoint, which is confusing. This is especially apparent following the below steps:

**To Reproduce**
1. `rio up -f belowfile.yaml`
```yaml
services:
  api:
    app: api
    version: v0
    concurrency: 10

    containers:
      - name: postfix-opendkim
        image: ibuildthecloud/demo:v1
        imagePullPolicy: IfNotPresent
        ports:
        - 80:80

      - name: api
        image: maxross/multiport:testing
        imagePullPolicy: IfNotPresent
        ports:
        - 8001:8001/http
        - 8002:8002/http
        env:
        - name: FOO
          value: BAR
        - name:  BAR
          value: BAZ
```
2. Wait for the service to become available, then run `rio ps`. Output for me:
```
NAME                 IMAGE                                    ENDPOINT                                                 PORTS                            SCALE     WEIGHT    CREATED          DETAIL
api                  ibuildthecloud/demo:v1                   https://api-v0-default.xxxxxx.on-rio.io                  80,8001,8002                     1         100%      25 minutes ago   
```

**Expected behavior**
The image being served by the endpoint in this case is actually `maxross/multiport:testing` since its exposed port is listed last in the list of ports. However, I did not specify any specific image on the rio service, so I would probably expect the `IMAGE` column to be either blank or show maxross/multiport:testing.

`rio v0.6.0` on k3s cluster with `kubernetes v1.16.2-k3s.1`
