### ISSUE TITLE
Cannot stage with edit a new service on one created with a Riofile

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#873]
**Describe the bug**
After creating a service with a Riofile, I cannot stage another service onto it using `rio stage --edit svc v2`

**To Reproduce**
1. `rio up -f belowfile.yaml`
```yaml
services:
  demo:
    app: demo
    version: v0
    image: ibuildthecloud/demo:v1
    ports:
    - 80
    env:
    - val=fooooo
```
2. Wait for the service to come up, then `rio stage --edit demo v3` and change the image to use `v3`. This will fail with:
```
#
# Error updating content:
#    The POST operation against Service.rio.cattle.io could not be completed at this time, please try again.
#
```

**Expected behavior**
I should be able to stage with edit on services created with a Riofile, without seeing this error.

Running on `rio v0.6.0`
