### ISSUE TITLE
build timeout in int brings up services but gives yaml errors and fails other functionalities

### ISSUE THREAD

**Issue by lucidprogrammer** [rancher/rio#881]
**Describe the bug**

**To Reproduce**
1. 

Consider the spec. 
```

services:
  scaletest:
    autoscale:
      concurrency: 10
      maxReplicas: 10
      minReplicas: 1
    ports:
    - 80:3000/http
    build:
     repo: https://github.com/riotesting/autoscale.git
     branch: master
     context: ./web
     timeout: 1200

```

rio up https://github.com/riotesting/autoscale

This will bring up the service absolutely fine with or without timeout variable in build. (however this is needed in some real services which has larger timeout requirement)

`kubectl -n rio-system logs -f $(kubectl -n rio-system get pods -l app=autoscaler -o name) autoscaler`
`E1202 01:46:49.843098       1 reflector.go:125] github.com/rancher/rio/pkg/generated/informers/externalversions/factory.go:118: Failed to list *v1.Service: v1.ServiceList.Items: []v1.Service: v1.Service.Spec: v1.ServiceSpec.PodConfig: Container: Ports: []v1.ContainerPort: PodConfig: Container: Image: PodConfig: Container: ImageBuild: v1.ImageBuildSpec.Timeout: unmarshalerDecoder: json: cannot unmarshal number into Go value of type string, error found in rancher/rio#10 byte of ...|eout":1200},"image":|..., bigger context ...|f74467e4d83a13a79b8f5ddf220210ea3f","timeout":1200},"image":"localhost:5442/some-scaletest:334e1","p|...`
**Expected behavior**

Run the autoscale test
This works fine if there was no timeout parameter.
Also, this one service with this issue will fail any other service in any other namespace too.
hey -z 600s -c 60 url

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
Type:
**Rio version**: `rio info`
```
latest
```
**Additional context**
`rio systemlogs`
output:
```

```
