### ISSUE TITLE
(REVISION) Need a way to get revision/gitcommit which can be used in a riofile

### ISSUE THREAD

**Issue by lucidprogrammer** [rancher/rio#894]
Note: Please add dashboard specific bugs to the dashboard repo: https://github.com/rancher/dashboard/issues

**Describe the bug**
Not a bug, its a much needed feature. In a similar manner, giving NAMESPACE, we need a way to get the current commit hash. Applicable in various docker use cases, we may need to provide labels, tag the build in the way needed etc.

**To Reproduce**
1. 

**Expected behavior**

**Kubernetes version & type (GKE, on-prem)**: `kubectl version`
```

```
Type:
**Rio version**: `rio info`
```

```
**Additional context**
`rio systemlogs`
output:
```

```

**Comment by rancher-max** [comment]
Working now in master. Example riofile that has a few different ways to do this. Note that with this example, due to the way the template was defined, both the environment variable `${REVISION}` and the gotemplate variable `{{.Values.Revision}}` are available:

```yaml
services:
  custrev:
    env:
    - name: FOO
      value: ${REVISION}
    - name: BAR
      value: BAZ
    - name: BAZ
      value: ${NAMESPACE}
    build:
      branch: master
      buildContext: .
      dockerfile: Dockerfile
      repo: https://github.com/rancher-max/rio-demo
      imageName: myname/custimage
    ports:
    - 8080
  custlocal:
    build:
      buildContext: ./blah/
      dockerfile: ./blah/Dockerfile
      imageName: localcontext/blahimage:{{ printf "%.7s" .Values.REVISION}}
    ports:
    - "8080"
  please:
    app: ${NAMESPACE}
    build:
      branch: master
      buildContext: .
      dockerfile: Dockerfile
      repo: https://github.com/rancher-max/rio-demo
    ports:
    - 8080

template:
  goTemplate: true # use go templating
  envSubst: true # use ENV vars during templating
  questions:  # now make some questions that we provide answers too
  - variable: FOO
    description: ""
  - variable: NAMESPACE
    description: "The namespace"
  - variable: REVISION
    description: "The revision"
```
