### ISSUE TITLE
Cannot create a route with a path to slash

### ISSUE THREAD

**Issue by rancher-max** [rancher/rio#902]
**Describe the bug**
Creating a router like `rio route add myroute/ to foo` does not respect the given slash and ends up with no path matching in the manifest.

**To Reproduce**
1. Create a service named foo
2. Create a router to that service with the above command
3. Inspect the route. It should have a spec like:
```yaml
spec:
  routes:
  - match:
      path:
        exact: /
    to:
    - app: foo
      version: v0
```
