### ISSUE TITLE
Build image should support image tag being set

### ISSUE THREAD

**Issue by cbron** [rancher/rio#918]
This riofile does not work because it tries to add a 2nd image tag to the end of `:dev`
```
services:
  revs:
    version: v1
    ports:
    - 8080
    build:
      branch: master
      buildContext: .
      dockerfile: Dockerfile
      repo: https://github.com/cbron/mybusybox
      imageName: ns/name:dev
```
