### ISSUE TITLE
Template service should respect and default a duration

### ISSUE THREAD

**Issue by cbron** [rancher/rio#924]
Right now a new service built from a template goes to 100% as soon as it is ready. Instead it should get a rollout duration of 1m, or something similar. Similarly, if I pass `--rollout-duration=1h` at the time I create the template service, every rollout after that should use the 1h duration time specified, this will require an extra API field.  

Need to test: 
* template with duration set and not-set
  * ` rio run  -p 8080 -n tpl --template --rollout-duration=0s ...`
  * ` rio run  -p 8080 -n tpl --template ...`
* weight
* promote
* rio run faux stage: `rio run --weight 50 --rollout-duration=30s -p 80 -n app@v3 nginx`

**Comment by rancher-max** [comment]
Also with this, the weight goes to 100 instead of 10000 when using template services. There's no weight value in template spec, but looking at the first version that is created from it:
```yaml
...
spec:
  app: temptag
  build:
    branch: master
    repo: https://github.com/rancher-max/rio-demo
    revision: vme-alpha-rc-things
    tag: true
    webhookSecretName: githubtoken
  image: localhost:5442/default/temptag-v0l9scf-ccd1159-59d8a:vme-a
  ports:
  - port: 8080
    targetPort: 8080
  weight: 100
status:
  appEndpoints:
  - https://temptag-default.xxxxxx.on-rio.io
  - http://temptag-default.xxxxxx.on-rio.io
  buildLogToken: c8rhbgsls7xnl5ql68vr9ngnh7g57hcgtj6npr7wqjnzpv7wb8xv9w
  computedApp: temptag
  computedVersion: 9ea7977d
  computedWeight: 100
...
```
