### ISSUE TITLE
How to redirect to https on same domain

### ISSUE THREAD

**Issue by kozy** [rancher/rio#992]
Hi guys, thanks for this highly useful tool

I am trying to do a protocol change. Simply redirect all http requests to the https variant, i.e. http://example.com -> https://example.com

Can someone provide me with an example of this? Can't figure it out. I am able to redirect to different domains but unable to differentiate, nor in the router, nor on the protocol.

I can do something like

```
  routes:
  - match: {}
    redirect:
      toHTTPS: true
```

But that results in a redirect loop.

Thanks!
